# We can have from zero to many running subscribers
# Each subscriber binds to these ports on all interfaces
subscriber:
  - ports: "5000-5099"

# We have only one publisher that sends blocks to its subscribers
publisher:
  - addr: "127.0.0.1"
    ports: "5000-5099"
